# Generated by Django 4.2 on 2023-04-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cabins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=255)),
                ("service_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("vat_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("area", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cabins.area")),
            ],
        ),
    ]
