# Generated by Django 4.2 on 2023-04-28 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0002_area_remove_postcode_id_alter_cabin_area_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabins.area'),
        ),
    ]
