# Generated by Django 4.2 on 2023-04-28 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0001_initial"),
        ("cabins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(null=True)),
                ("canceled_at", models.DateTimeField(null=True)),
                ("cabin", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cabins.cabin")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="owner", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("services", models.ManyToManyField(blank=True, to="services.service")),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(null=True)),
                ("canceled_at", models.DateTimeField(null=True)),
                (
                    "reservation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reservations.reservation"),
                ),
            ],
        ),
    ]
