# Generated by Django 4.2 on 2023-04-26 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="customer", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="owner", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reservation",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reservations.reservation"),
        ),
    ]
