# Generated by Django 4.1.3 on 2023-05-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0002_invoice_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
