# Generated by Django 4.2 on 2023-04-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("area", models.CharField(max_length=100)),
                ("post_code", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="PostCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("postal_district", models.CharField(max_length=45)),
                ("p_code", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cabins.areacode")),
            ],
        ),
        migrations.CreateModel(
            name="Cabin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                ("description", models.TextField(max_length=255)),
                ("price_per_night", models.DecimalField(decimal_places=2, max_digits=8)),
                ("num_of_beds", models.IntegerField()),
                ("area", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cabins.areacode")),
                ("zip_code", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cabins.postcode")),
            ],
        ),
    ]
