# Generated by Django 4.2 on 2023-04-28 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='postcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='cabin',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabins.area'),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='p_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cabins.area'),
        ),
    ]
