# Generated by Django 4.2 on 2023-05-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cabins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cabin",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
