# Generated by Django 4.2 on 2023-04-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_area'),
        ('cabins', '0002_area_remove_postcode_id_alter_cabin_area_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaCode',
        ),
    ]
