# Generated by Django 4.2 on 2023-04-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0003_delete_areacode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcode',
            name='p_code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
